# Generated by Django 3.2.16 on 2022-10-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221017_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
