# Generated by Django 3.2.16 on 2022-10-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
