# Generated by Django 3.2.16 on 2022-10-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_requirements_what_you_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='points',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='what_you_learn',
            name='points',
            field=models.CharField(max_length=500),
        ),
    ]
