# Generated by Django 3.2.16 on 2022-10-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload',
            field=models.FileField(null=True, upload_to='Files/'),
        ),
    ]
