# Generated by Django 3.2.16 on 2022-10-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_video_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(null=True, upload_to='File/filedepost'),
        ),
    ]
