# Generated by Django 3.2.16 on 2022-10-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
