# Generated by Django 3.2.16 on 2022-10-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20221020_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='totalrate',
            field=models.FloatField(default=0),
        ),
    ]
