# Generated by Django 3.2.16 on 2022-10-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_reviewrating_totalrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='totalrate',
        ),
    ]
