# Generated by Django 3.2.16 on 2022-10-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20221021_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
