# Generated by Django 3.2.16 on 2022-10-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20221020_0110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
