# Generated by Django 3.2.16 on 2022-10-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20221021_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
